title: eXperience Points Japan
description: >- # this means to ignore newlines until "baseurl:"
   eXperience Pointsはゲーム報酬に特化された仮想通貨です。
   ブロックチェーン技術をあらゆるゲームに取り入れることを可能にします。
   また、スポーツや教育分野も私たちのターゲットです。
   それらの実現を目指し日々開発を続けております。
baseurl: "" # the subpath of your site, e.g. /blog

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%Y/%m/%d %H:%M"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html
exclude:
  - Gemfile
  - Gemfile.lock

# Build settings
markdown: kramdown
theme: minima
google_analytics: UA-111302890-1

collections:
  faqs:
  shops:

plugins: 
  - jekyll-paginate
  - jekyll-seo-tag

paginate: 7
paginate_path: "/page:num"
